#!/bin/sh

# Modified from https://github.com/andrewseidl/githook-clang-format
# Use the following command to activate it on your local instance of the repo.
# cd .git/hooks && ln -s ../../utils/hooks/pre-commit

format_file() {
  file="$1"
  if [ -f "$file" ]; then
    clang-format -i "$file"
    git add "$file"
  fi
}

case "$1" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in "$(git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$')"; do
      format_file "$file"
    done
    ;;
esac
