/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "outputWriter/XYZWriter.h"
#include "Particle.h"

#include <fstream>
#include <iomanip>
#include <ios>
#include <span>
#include <sstream>
#include <string_view>

namespace outputWriter::XYZWriter {
void plotParticles(std::span<const Particle> particles, std::string_view filename, unsigned iteration) {
	std::ofstream file;
	std::stringstream strstr;
	strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

	file.open(strstr.str().c_str());
	file << particles.size() << '\n';
	file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
			"file format doku.\n";

	for (const auto& p : particles) {
		file << "Ar ";
		file.setf(std::ios_base::showpoint);

		for (const auto& xi : p.x) {
			file << xi << " ";
		}

		file << '\n';
	}

	file.close();
}
}  // namespace outputWriter::XYZWriter
