#pragma once

#define LOG_FORCES 1
#define LOG_INTERACTION_ITER 0
#define LOG_PARTICLE_CONTAINER 0
#define LOG_BORDER_CELL_ITER 0
#define LOG_SPECIAL_MEMFUNS 0
#define LOG_SIM 1
#define LOG_SIM_STATE 0
#define LOG_GRID 0
#define LOG_INPUT_PARSING 0
#define LOG_PERIODIC 0
#define LOG_THERMOSTAT 0
#define LOG_CHECKPOINT 0
#define LOG_RANDOM 0
#define LOG_MEMBRANE 1
#define LOG_MEMBRANE_NEIGHBORS 0
#define LOG_HARMONIC 1
