#pragma once

#define LOG_FORCES 0
#define LOG_INTERACTION_ITER 0
#define LOG_PARTICLE_CONTAINER 0
#define LOG_BORDER_CELL_ITER 0
#define LOG_SPECIAL_MEMFUNS 1
#define LOG_SIM 0
#define LOG_GRID 0
#define LOG_INPUT_PARSING 0
#define LOG_PARTICLE_TYPE 0
