/*
 * Particle.h
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#pragma once

#include <array>
#include <iostream>
#include <source_location>
#include <string>
#include <type_traits>

#include "Vector.h"

class Particle {
private:
	/**
	 * Position of the particle
	 */
	vec x;

	/**
	 * Velocity of the particle
	 */
	vec v;

	/**
	 * Force effective on this particle
	 */
	vec f{};

	/**
	 * Force which was effective on this particle
	 */
	vec old_f{};

	/**
	 * Mass of this particle
	 */
	double m;

	/**
	 * Type of the particle. Use it for whatever you want (e.g. to separate
	 * molecules belonging to different bodies, matters, and so on)
	 */
	int type;

	constexpr void runtime_log(std::string_view msg) {
		if (!std::is_constant_evaluated()) {
			std::cout << msg;
		}
	}

	constexpr void log_special_mem(std::string_view by, const std::source_location& location) {
		runtime_log(
			std::format(
				"{}:{}:{}: Particle generated by {}!\n", location.file_name(), location.line(), location.column(), by
			)
		);
	}

public:
	constexpr explicit Particle(
		int type_arg = 0, const std::source_location& loc = std::source_location::current()
	) noexcept
		: type(type_arg) {
		log_special_mem("default construction", loc);
	}

	constexpr Particle(
		const Particle& other, const std::source_location& loc = std::source_location::current()
	) noexcept
		: x(other.x)
		, v(other.v)
		, f(other.f)
		, old_f(other.old_f)
		, m(other.m)
		, type(other.type) {
		log_special_mem("copy", loc);
	}

	constexpr Particle(Particle&& other, const std::source_location& loc = std::source_location::current()) noexcept
		: x(std::move(other.x))
		, v(std::move(other.v))
		, f(std::move(other.f))
		, old_f(std::move(other.old_f))
		, m(other.m)
		, type(other.type) {
		log_special_mem("move", loc);
	}

	constexpr Particle& operator=(const Particle& other) noexcept {
		x = other.x;
		v = other.v;
		f = other.f;
		old_f = other.old_f;
		m = other.m;
		type = other.type;
		runtime_log("Particle generated by copy assignment!\n");
		return *this;
	}

	constexpr Particle& operator=(Particle&& other) noexcept {
		x = std::move(other.x);
		v = std::move(other.v);
		f = std::move(other.f);
		old_f = std::move(other.old_f);
		m = other.m;
		type = other.type;
		runtime_log("Particle generated by move assignment!\n");
		return *this;
	}

	// for visualization, we need always 3 coordinates
	// -> in case of 2d, we use only the first and the second

	constexpr Particle(
		vec x_arg, vec v_arg, double m_arg, int type_arg = 0,
		const std::source_location& loc = std::source_location::current()
	) noexcept
		: x(std::move(x_arg))
		, v(std::move(v_arg))
		, m(m_arg)
		, type(type_arg)

	{
		log_special_mem("parameterized construction", loc);
	}

	constexpr virtual ~Particle() noexcept {
		runtime_log("Particle destructed!\n");
	}

	constexpr const vec& getX() const {
		return x;
	}

	constexpr void setX(const vec new_x) noexcept {
		x = new_x;
	}

	constexpr const vec& getV() const {
		return v;
	}

	constexpr void setV(const vec& new_v) noexcept {
		v = new_v;
	}

	constexpr const vec& getF() const {
		return f;
	}

	constexpr void setF(const vec& new_f) noexcept {
		f = new_f;
	}

	constexpr const vec& getOldF() const {
		return old_f;
	}

	constexpr void setOldF(const vec& new_old_f) noexcept {
		old_f = new_old_f;
	}

	constexpr double getM() const {
		return m;
	}

	constexpr int getType() const {
		return type;
	}

	constexpr bool operator==(const Particle& other) const = default;

	// https://quick-bench.com/q/qDcxmk_OjShhSwf_VKAQ_6abBwE
	std::string toString() const {
		std::string result;
		std::format_to(
			std::back_inserter(result), "Particle X: {} v: {} f: {} old_f: {} type: {}", x, v, f, old_f, type
		);
		return result;
	}
};

constexpr std::ostream& operator<<(std::ostream& stream, Particle& p) {
	stream << p.toString();
	return stream;
}
