/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <iostream>

#include "utils/ArrayUtils.h"
#include "Vector.h"

Particle::Particle(int type_arg)
	: type(type_arg) {
	std::cout << "Particle generated!" << std::endl;
}

Particle::Particle(const Particle& other)
	: x(other.x)
	, v(other.v)
	, f(other.f)
	, old_f(other.old_f)
	, m(other.m)
	, type(other.type) {
	std::cout << "Particle generated by copy!" << std::endl;
}

// Todo: maybe use initializater list instead of copy?
Particle::Particle(vec x_arg, vec v_arg, double m_arg, int type_arg)
	: x(std::move(x_arg))
	, v(std::move(v_arg))
	, m(m_arg)
	, type(type_arg)

{
	std::cout << "Particle generated!" << std::endl;
}

Particle::~Particle() {
	std::cout << "Particle destructed!" << std::endl;
}

const vec& Particle::getX() const {
	return x;
}

const vec& Particle::getV() const {
	return v;
}

const vec& Particle::getF() const {
	return f;
}

const vec& Particle::getOldF() const {
	return old_f;
}

double Particle::getM() const {
	return m;
}

int Particle::getType() const {
	return type;
}

void Particle::setF(const vec& new_f) noexcept {
	f = new_f;
}

void Particle::setOldF(const vec& new_f) noexcept {
	old_f = new_f;
}

void Particle::setV(const vec& new_v) noexcept {
	v = new_v;
}

void Particle::setX(const vec& new_x) noexcept {
	x = new_x;
}

std::string Particle::toString() const {
	std::stringstream stream;
	stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
	return stream.str();
}

std::ostream& operator<<(std::ostream& stream, Particle& p) {
	stream << p.toString();
	return stream;
}
